### PR TITLE
Fix #9 & Fix #11

### LINKED ISSUE #9: Using template Nativescript-Vue-Web error in iOS
If you use this template, in the `App.vue` file, needs to import the component HelloWorld. Otherwise there will be an error when you try the app in iOS.

Needs proper import 
```
import HelloWorld from './components/HelloWorld';
components: {
   HelloWorld,
}
```

### LINKED ISSUE #11: Error when installing plugin to project using vue-cli 3
I tried using `vue create project-name` as well as `vue ui` with default preset (babel, eslint) as well as default plugin options to create my project but I'm still receiving this error.

```
$ npm --version
6.9.0
$ npm list -g --depth=0
@vue/cli@3.6.3
```

```
+ vue-cli-plugin-nativescript-vue@0.0.14
added 18 packages from 6 contributors and audited 24842 packages in 14.756s
found 0 vulnerabilities

 ERROR  TypeError: Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at module.exports.extractCallDir (/home/aes/Sandbox/zen-code-sharing/node_modules/vue-cli-plugin-nativescript-vue/generator/index.js:907:78)
    at module.exports.renderDirectoryStructure (/home/aes/Sandbox/zen-code-sharing/node_modules/vue-cli-plugin-nativescript-vue/generator/index.js:847:27)
    at /home/aes/Sandbox/zen-code-sharing/node_modules/vue-cli-plugin-nativescript-vue/generator/index.js:199:11
    at Generator.resolveFiles (/usr/lib/node_modules/@vue/cli/lib/Generator.js:209:13)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async Generator.generate (/usr/lib/node_modules/@vue/cli/lib/Generator.js:116:5)
    at async runGenerator (/usr/lib/node_modules/@vue/cli/lib/invoke.js:133:3)
    at async invoke (/usr/lib/node_modules/@vue/cli/lib/invoke.js:117:3)
Error: Command failed: vue invoke vue-cli-plugin-nativescript-vue --$inlineOptions {"applicationId":"org.nativescript.application","historyMode":false,"isNewProject":true,"isNativeOnly":false,"templateType":"simple"}
adding to package.json
deleting from package.json
doing template rendering

🚀  Invoking generator for vue-cli-plugin-nativescript-vue...

    at makeError (/usr/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at /usr/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  code: 1,
  stdout: 'adding to package.json\ndeleting from package.json\ndoing template ' +
    'rendering\n\n🚀  Invoking generator for ' +
    'vue-cli-plugin-nativescript-vue...\n',
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'vue invoke vue-cli-plugin-nativescript-vue --$inlineOptions ' +
    '{"applicationId":"org.nativescript.application","historyMode":false,"isNewProject":true,"isNativeOnly":false,"templateType":"simple"}',
  timedOut: false,
  killed: false
}
```

package.json
```
{
  "name": "zen-code-sharing",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^2.6.5",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.6.0",
    "@vue/cli-plugin-eslint": "^3.6.0",
    "@vue/cli-service": "^3.6.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-cli-plugin-nativescript-vue": "0.0.14",
    "vue-template-compiler": "^2.5.21"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

### PR DESCRIPTION
**Pull request by jawa-the-hutt**
Fix #9 -  add Helloworld import
Fix #11 - fix extractCallDir for npm 6.9.0

### CODE REVIEW

File: generator/index.js [hunk 1]
```diff
@@ -904,7 +904,13 @@ const extractCallDir = (module.exports.extractCallDir = () => {
   try {
     const obj = {};
     Error.captureStackTrace(obj);
-    return path.dirname(obj.stack.split('\n')[3].match(/\s\((.*):\d+:\d+\)$/)[1]);
+    const callSite = obj.stack.split('\n')[3];
+    let { fileName } = /(?<fileName>[^(\s]+):[0-9]+:[0-9]+/.exec(callSite).groups;
```
Comment (wmorawski) [inline generator/index.js:908]: SyntaxError: Invalid regular expression: /(?<fileName>[^(\s]+):[0-9]+:[0-9]+/: Invalid group
